### ISSUE TITLE
Google Map API key expire

### ISSUE THREAD

**Issue by tsaoyu** [WRSC/tracking#20]
The tracking page could load Google Maps correctly due to the API key issue. 

![image](https://user-images.githubusercontent.com/6488896/44260083-4faedd00-a20b-11e8-8f9c-cdaf26643484.png)

Error links to [here]( https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors)

**Comment by Nanoseb** [comment]
Ah yes, it's because google maps is not free anymore :/ not sure how easy is it to move to osm

**Comment by tsaoyu** [comment]
Got some trail credit from G-cloud and also a new API key.
