### ISSUE TITLE
Wrong PIN code

### ISSUE THREAD

**Issue by tsaoyu** [WRSC/tracking#21]
The default PIN code of giffgaff is 5555 according to [here](https://community.giffgaff.com/t5/Solve-your-questions/What-is-the-default-PIN-for-my-giffgaff-SIM/ta-p/3511073). 

I suspect our test SIM card is already locked due a wrong PIN is entered three times.

**Comment by Nanoseb** [comment]
From https://community.giffgaff.com/t5/Help-Support/How-do-I-get-the-sim-unlock-pin/td-p/15071247
> The default giffgaff PIN is 5555, but PIN protection is turned off when you get the SIM, so the PIN is not needed when you put it in a phone for the first time.

Not sure if that's true, but when we boot the device it always says "+CPIN: READY" so I guess that's all right.

**Comment by tsaoyu** [comment]
Giffgaff does not need PIN code to unlock SIM card.
Caveats were written in wiki
