### ISSUE TITLE
Store tracker token in database

### ISSUE THREAD

**Issue by saerdnaer** [WRSC/tracking#33]
As of now the tracker token is only stored during runtime of the rails app in RAM. To be able to redeploy the rails app during an event, these tokens have to be stored in the database. Otherwise the users have to reconfigure all tracking devices with the new tokens, each time the rails app restarts.

**Comment by takluyver** [comment]
If we can figure out this and issue #31, I think we should fix them and go through setting all the token IDs once; #31 effectively blocks the collaboration feature we wanted for the area scanning challenge.

**Comment by saerdnaer** [comment]
Checked Tony's assumptions: tokens where already stored in the database.
