### ISSUE TITLE
Tracker firmware: write CSV directly?

### ISSUE THREAD

**Issue by takluyver** [WRSC/tracking#42]
The tracker firmware currently writes each field (latitude, longitude, datetime...) into a separate file, separating values with underscores. When we pull this off, I have reprocessed it into CSVs for convenience. I think it should be possible to write CSV files directly, which would simplify getting and using the data.

**Comment by saerdnaer** [comment]
Definitly. (I had the same Idea...)
Can you specify the format the tracker should write to the CSV file?

**Comment by takluyver** [comment]
I would use the format I converted the data to for scoring. I converted the timestamp to ISO 8601 format (like `2018-08-27T12:31:01Z`) and kept the other 4 fields it recorded as they were.

- [Conversion script](https://github.com/WRSC/coordinates2018/blob/master/combine_tracker_logs.py)
- [Example CSV](https://github.com/WRSC/coordinates2018/blob/master/fleet-race/Southampton2.csv)

**Comment by tsaoyu** [comment]
Done in 69401a5, tested on the tracker.
